INSERT INTO series (title, author_id, subgenre_id) VALUES ("A Song of Ice and Fire", 1, 1);
INSERT INTO subgenres (name) VALUES ("Sword & Sorcery");
INSERT INTO authors (name) VALUES ("George R. R. Martin");
INSERT INTO books (title, year, series_id) VALUES ("A Game of Thrones", 1996, 1);
INSERT INTO books (title, year, series_id) VALUES ("A Clash of Kings", 1998, 1);
INSERT INTO books (title, year, series_id) VALUES ("A Storm of Swords", 2000, 1);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Ned Stark", "Winter is coming.", "Human", 1, 1);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Jaqen H'ghar", "Valar morghulis.", "Human", 1, 1);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Daenerys Targaryen", "Mother of dragons.", "Human", 1, 1);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Tyrion Lannister", "A Lannister always pays his debts.", "Human", 1, 1);
INSERT INTO character_books (character_id, book_id) VALUES (1, 1);
INSERT INTO character_books (character_id, book_id) VALUES (2, 2);
INSERT INTO character_books (character_id, book_id) VALUES (3, 1);
INSERT INTO character_books (character_id, book_id) VALUES (3, 2);
INSERT INTO character_books (character_id, book_id) VALUES (3, 3);
INSERT INTO character_books (character_id, book_id) VALUES (4, 1);
INSERT INTO character_books (character_id, book_id) VALUES (4, 2);
INSERT INTO character_books (character_id, book_id) VALUES (4, 3);
INSERT INTO series (title, author_id, subgenre_id) VALUES ("Temeraire", 2, 2);
INSERT INTO subgenres (name) VALUES ("Alternate History");
INSERT INTO authors (name) VALUES ("Naomi Novik");
INSERT INTO books (title, year, series_id) VALUES ("His Majesty's Dragon", 2006, 2);
INSERT INTO books (title, year, series_id) VALUES ("Throne of Jade", 2006, 2);
INSERT INTO books (title, year, series_id) VALUES ("Black Powder War", 2006, 2);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Mianning", NULL, "Human", 2, 2);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Avraam Maden", NULL, "Human", 2, 2);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Temeraire", "Bold.", "Dragon", 2, 2);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Captain William Laurence", "Steady.", "Human", 2, 2);
INSERT INTO character_books (character_id, book_id) VALUES (5, 5);
INSERT INTO character_books (character_id, book_id) VALUES (6, 6);
INSERT INTO character_books (character_id, book_id) VALUES (7, 4);
INSERT INTO character_books (character_id, book_id) VALUES (7, 5);
INSERT INTO character_books (character_id, book_id) VALUES (7, 6);
INSERT INTO character_books (character_id, book_id) VALUES (8, 4);
INSERT INTO character_books (character_id, book_id) VALUES (8, 5);
INSERT INTO character_books (character_id, book_id) VALUES (8, 6);